sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip3 install pipenv codecov --upgrade
  - pipenv install

script:
  - coverage run tests/test_dora.py

after_success:
  - codecov
